---
apiVersion: v1
kind: Service
metadata:
  name: appback-article-svc
  labels:
    app: "appback-article"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: appback-article