---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: appback-article
  name: appback-article
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appback-article
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: appback-article
    spec:
      containers:
        - name: appBackArticle
          image: lgomezs/appback-article
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: AZURE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: appback-article-secrets
                  key: AZURE_CLIENT_ID
            - name: AZURE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: appback-article-secrets
                  key: AZURE_CLIENT_SECRET
            - name: AZURE_KEYVAULT_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: appback-article-secrets
                  key: AZURE_KEYVAULT_ENDPOINT
            - name: AZURE_TENANT_ID
              valueFrom:
                secretKeyRef:
                  name: appback-article-secrets
                  key: AZURE_TENANT_ID
            - name: PROFILE
              value: dev
      imagePullSecrets:
        - name: regcred