---
apiVersion: v1
kind: Service
metadata:
  name: appBackArticle-svc
  labels:
    app: "appBackArticle"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: appBackArticle