apiVersion: v1
kind: Secret
metadata:
  name: appback-article-secrets
type: Opaque
data:
  AZURE_CLIENT_ID: Y2UwZGNkNDgtNmY5YS00MGFiLTkyYjUtNTA4ZGMwMWY4Zjdm
  AZURE_CLIENT_SECRET: ZWgxOFF+N091NTBiWFFwVWFiNmtCRDZzZ2w2eFlOOEhnUTZHT2JTUQ==
  AZURE_KEYVAULT_ENDPOINT: aHR0cHM6Ly9rdi1yZy1kZXYxLnZhdWx0LmF6dXJlLm5ldC8=
  AZURE_TENANT_ID: NGU4NzExYjUtMWVkYy00NGY4LTg0YzItZDkzZTljYmIyNjUw